_wandb:
    value:
        cli_version: 0.24.2
        e:
            howu5a96s17jlli2iq2l092pblo0r9fi:
                args:
                    - --train_shards
                    - /scratch/aparame/Research/VLCM_Data_Collection/data_scratch
                    - --dataset_type
                    - rware
                    - --rware_config
                    - mixed-rware
                    - --batch_size
                    - "2"
                    - --grad_accum_steps
                    - "8"
                    - --clip_len
                    - "5"
                    - --num_robots
                    - "4"
                    - --robot_obs_dim
                    - "6"
                    - --epochs
                    - "50"
                    - --vl_backend
                    - llava_video
                    - --vl_model_name
                    - llava-hf/LLaVA-NeXT-Video-7B-32K-hf
                    - --save_dir
                    - /scratch/aparame/Research/VLCM_checkpoints
                    - --num_workers
                    - "4"
                    - --mixed_precision
                    - bf16
                    - --freeze_vl
                    - --peft
                    - lora
                    - --lora_r
                    - "8"
                    - --lora_alpha
                    - "16"
                    - --lora_dropout
                    - "0.05"
                    - --vision_lr
                    - "1e-5"
                    - --loss_type
                    - contrastive_mse
                    - --mse_loss_weight
                    - "1.0"
                    - --vl_max_text_len
                    - "1024"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 104
                cpu_count_logical: 104
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "67108864"
                        used: "16384"
                email: aparame@g.clemson.edu
                executable: /usr/bin/python3
                git:
                    commit: 92c244cffc6b81c8c727f3707fbda12bef12343f
                    remote: git@github.com:shahils01/MA-VLCM.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-74f0268e-a4a5-f89d-c3bb-264a78d60d0e
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-804512ca-c17f-baa3-2806-8fcd69cc3b4d
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-2a0348b2-461f-58d7-cd49-757591651dfd
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-8265e80b-93f8-3175-2dbc-755a1b8c7712
                host: nodeai03.palmetto.clemson.edu
                memory:
                    total: "1081133432832"
                os: Linux-4.18.0-553.50.1.el8_10.x86_64-x86_64-with-glibc2.35
                program: /home/aparame/Research/MA-VLCM/train.py
                python: CPython 3.10.12
                root: /home/aparame/Research/MA-VLCM
                slurm:
                    cluster_name: palmetto2
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus: h100:4
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: cuuser_yue6_vae_verification
                    job_cpus_per_node: "32"
                    job_end_time: "1771962483"
                    job_gid: "10000"
                    job_gpus: 2,4,6,7
                    job_id: "9740112"
                    job_name: ma_vlcm_train
                    job_nodelist: nodeai03
                    job_num_nodes: "1"
                    job_partition: work1
                    job_qos: normal
                    job_start_time: "1771703283"
                    job_uid: "432600"
                    job_user: aparame
                    jobid: "9740112"
                    localid: "0"
                    mem_per_node: "262144"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nodeai03
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nodeai03
                    submit_dir: /home/aparame/Research/MA-VLCM
                    submit_host: vm-slurm-p-login02.palmetto.clemson.edu
                    task_pid: "3674599"
                    tasks_per_node: "1"
                    topology_addr: ndrspine.aindrspine.aindrleaf1.nodeai03
                    topology_addr_pattern: switch.switch.switch.node
                    tres_per_task: cpu=32
                startedAt: "2026-02-21T19:48:13.730825Z"
                writerId: howu5a96s17jlli2iq2l092pblo0r9fi
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 49
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 77
                - 98
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.24.2
            "8":
                - 2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 2
clip_len:
    value: 5
clip_stride:
    value: 1
compile:
    value: false
contrastive_margin:
    value: 0
d_model:
    value: 256
dataset_type:
    value: rware
ddp_find_unused_parameters:
    value: false
debug_out_dir:
    value: debug_samples
debug_save_video:
    value: false
done_reduce:
    value: any
epochs:
    value: 50
freeze_vision_tower:
    value: false
freeze_vl:
    value: true
fsdp:
    value: false
fsdp_cpu_offload:
    value: false
fsdp_min_num_params:
    value: 1000000
fsdp_use_orig_params:
    value: false
fusion_hidden:
    value: 512
gamma:
    value: 0.99
gnn_layers:
    value: 2
grad_accum_steps:
    value: 8
log_every:
    value: 50
lora_alpha:
    value: 16
lora_bias:
    value: none
lora_dropout:
    value: 0.05
lora_r:
    value: 8
lora_target_modules:
    value: ""
loss_type:
    value: contrastive_mse
lr:
    value: 0.0003
mixed_precision:
    value: bf16
moe_experts:
    value: 4
moe_top_k:
    value: 2
mse_loss_weight:
    value: 1
n_step:
    value: 50
num_robots:
    value: 4
num_workers:
    value: 4
peft:
    value: lora
preprocess_in_loader:
    value: true
quantization_config:
    value: null
resize_height:
    value: 336
resize_width:
    value: 672
return_mode:
    value: td
reward_reduce:
    value: mean
robot_obs_dim:
    value: 6
robot_source:
    value: obs
rware_config:
    value: mixed-rware
samples_per_epoch:
    value: 1000
save_dir:
    value: /scratch/aparame/Research/VLCM_checkpoints
temporal_dropout:
    value: 0.1
temporal_heads:
    value: 4
temporal_layers:
    value: 2
text_dim:
    value: 512
text_mode:
    value: raw
text_prompt_template:
    value: null
train_shards:
    value: /scratch/aparame/Research/VLCM_Data_Collection/data_scratch
use_moe:
    value: false
val_shards:
    value: ""
video_channels:
    value: 3
video_frames:
    value: 8
video_mean:
    value:
        - 0.5
        - 0.5
        - 0.5
video_preprocessed:
    value: true
video_std:
    value:
        - 0.5
        - 0.5
        - 0.5
vision_lr:
    value: 1e-05
vl_backend:
    value: llava_video
vl_dtype:
    value: bfloat16
vl_max_text_len:
    value: 1024
vl_model_name:
    value: llava-hf/LLaVA-NeXT-Video-7B-32K-hf
weight_decay:
    value: 0.01
