_wandb:
    value:
        cli_version: 0.24.2
        e:
            g0z2eiodfktjnbwukuoj0kos9g2bnyhp:
                args:
                    - --train_shards
                    - /scratch/shahils/data/wds_gotogoal/shard-{000000..000080}.tar
                    - --batch_size
                    - "3"
                    - --epochs
                    - "500"
                    - --clip_len
                    - "5"
                    - --clip_stride
                    - "5"
                    - --robot_source
                    - obs
                    - --reward_reduce
                    - mean
                    - --done_reduce
                    - any
                    - --gamma
                    - "0.99"
                    - --text_mode
                    - raw
                    - --return_mode
                    - nstep
                    - --n_step
                    - "5"
                    - --vl_backend
                    - llava_video
                    - --vl_model_name
                    - llava-hf/LLaVA-NeXT-Video-7B-hf
                    - --text_prompt_template
                    - 'You are a critic model. The video of a team of robots (denoted as circular dots  with heading denoted by an arrow) is: <video>, and the robot team observations over ten episodes is <obs>.  The goal for each robot is denoted by the same color square box. The robots have to go to their designated goal   without colliding with one another. They also have to be efficient by taking the shortest parth. How Good or Bad are   the team of robots doing to accomplish the given task?'
                    - --peft
                    - lora
                    - --lora_r
                    - "16"
                    - --lora_alpha
                    - "32"
                    - --lora_dropout
                    - "0.05"
                    - --wandb
                    - --wandb_project
                    - ma-vlcm
                    - --wandb_run_name
                    - ma-vlcm-ddp
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "53660876800"
                        used: "15293136896"
                email: shahil.shaik7@gmail.com
                executable: /home/shahils/.conda/envs/llava_video/bin/python3.10
                git:
                    commit: 0a234cf975aeb3f3cc27b113732d92aab078208f
                    remote: git@github.com:shahils01/MA-VLCM.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-f76bf313-999c-cb10-0b31-afe0a14f4831
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-990cb3da-b462-abf0-0569-33c130b1bcc3
                host: node0406.palmetto.clemson.edu
                memory:
                    total: "269207310336"
                os: Linux-4.18.0-553.50.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /scratch/shahils/MA-VLCM/train.py
                python: CPython 3.10.19
                root: /scratch/shahils/MA-VLCM
                slurm:
                    cluster_name: palmetto2
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "2"
                    gpus_per_node: a100:2
                    gtids: "0"
                    job_account: cuuser_yue6_imitation_learning_shahil
                    job_cpus_per_node: "32"
                    job_end_time: "1771647366"
                    job_gid: "10000"
                    job_gpus: 0,1
                    job_id: "9671655"
                    job_name: interactive
                    job_nodelist: node0406
                    job_num_nodes: "1"
                    job_partition: interact
                    job_qos: normal
                    job_start_time: "1771604166"
                    job_uid: "359706"
                    job_user: shahils
                    jobid: "9671655"
                    launch_node_ipaddr: 10.125.60.106
                    localid: "0"
                    mem_per_node: "102400"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: node0406
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "63166"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "60943"
                    pty_win_col: "204"
                    pty_win_row: "53"
                    script_context: prolog_task
                    srun_comm_host: 10.125.60.106
                    srun_comm_port: "62307"
                    step_id: "4294967290"
                    step_launcher_port: "62307"
                    step_nodelist: node0406
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    stepmgr: node0406
                    submit_dir: /scratch/shahils/MA-VLCM
                    submit_host: vm-slurm-p-login01.palmetto.clemson.edu
                    task_pid: "3947586"
                    tasks_per_node: "1"
                    topology_addr: ndrspine.hdrspine.hdrleaf4.node0406
                    topology_addr_pattern: switch.switch.switch.node
                    tres_per_task: cpu=32
                startedAt: "2026-02-20T17:44:46.652387Z"
                writerId: g0z2eiodfktjnbwukuoj0kos9g2bnyhp
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 77
                - 98
            "3":
                - 13
            "4": 3.10.19
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 3
clip_len:
    value: 5
clip_stride:
    value: 5
contrastive_margin:
    value: 0
d_model:
    value: 256
data_backend:
    value: webdataset
ddp_find_unused_parameters:
    value: false
debug_out_dir:
    value: debug_samples
debug_save_video:
    value: false
done_reduce:
    value: any
epochs:
    value: 500
freeze_vl:
    value: false
fsdp:
    value: false
fsdp_cpu_offload:
    value: false
fsdp_min_num_params:
    value: 1000000
fsdp_use_orig_params:
    value: false
fusion_hidden:
    value: 512
gamma:
    value: 0.99
gnn_layers:
    value: 2
grad_accum_steps:
    value: 1
hf_config:
    value: ""
hf_dataset:
    value: ""
hf_streaming:
    value: false
hf_train_split:
    value: train
hf_val_split:
    value: ""
log_every:
    value: 50
lora_alpha:
    value: 32
lora_bias:
    value: none
lora_dropout:
    value: 0.05
lora_r:
    value: 16
lora_target_modules:
    value: ""
loss_type:
    value: contrastive
lr:
    value: 0.0003
mixed_precision:
    value: "no"
moe_experts:
    value: 4
moe_top_k:
    value: 2
n_step:
    value: 5
num_robots:
    value: 5
num_workers:
    value: 4
peft:
    value: lora
preprocess_in_loader:
    value: true
quantization_config:
    value: null
return_mode:
    value: nstep
reward_reduce:
    value: mean
robot_obs_dim:
    value: 40
robot_source:
    value: obs
samples_per_epoch:
    value: 10000
save_dir:
    value: checkpoints
temporal_dropout:
    value: 0.1
temporal_heads:
    value: 4
temporal_layers:
    value: 2
text_dim:
    value: 512
text_mode:
    value: raw
text_prompt_template:
    value: 'You are a critic model. The video of a team of robots (denoted as circular dots  with heading denoted by an arrow) is: <video>, and the robot team observations over ten episodes is <obs>.  The goal for each robot is denoted by the same color square box. The robots have to go to their designated goal   without colliding with one another. They also have to be efficient by taking the shortest parth. How Good or Bad are   the team of robots doing to accomplish the given task?'
train_shards:
    value: /scratch/shahils/data/wds_gotogoal/shard-{000000..000080}.tar
use_moe:
    value: false
val_shards:
    value: ""
video_channels:
    value: 3
video_frames:
    value: 100
video_height:
    value: 224
video_mean:
    value:
        - 0.5
        - 0.5
        - 0.5
video_preprocessed:
    value: true
video_std:
    value:
        - 0.5
        - 0.5
        - 0.5
video_width:
    value: 224
vl_backend:
    value: llava_video
vl_dtype:
    value: bfloat16
vl_max_text_len:
    value: 256
vl_model_name:
    value: llava-hf/LLaVA-NeXT-Video-7B-hf
wandb:
    value: true
wandb_entity:
    value: ""
wandb_project:
    value: ma-vlcm
wandb_run_name:
    value: ma-vlcm-ddp
wandb_tags:
    value: ""
weight_decay:
    value: 0.01
