_wandb:
    value:
        cli_version: 0.24.2
        e:
            zxp9grbtejh7bczqjxjho4k3tlg8jpdf:
                args:
                    - --train_shards
                    - /scratch/aparame/Research/VLCM_Data_Collection/RWARE/data_scratch
                    - --offroad_shards
                    - /scratch/aparame/Research/VLCM_Data_Collection/OFFROAD/dataset_2
                    - --offroad_num_robots
                    - "5"
                    - --dataset_type
                    - rware
                    - --rware_config
                    - mixed-rware
                    - --batch_size
                    - "6"
                    - --grad_accum_steps
                    - "2"
                    - --clip_len
                    - "16"
                    - --num_robots
                    - "5"
                    - --robot_obs_dim
                    - "8"
                    - --epochs
                    - "10"
                    - --vl_backend
                    - llava_video
                    - --vl_model_name
                    - llava-hf/LLaVA-NeXT-Video-7B-32K-hf
                    - --save_dir
                    - /scratch/aparame/Research/VLCM_checkpoints
                    - --num_workers
                    - "16"
                    - --mixed_precision
                    - bf16
                    - --freeze_vl
                    - --peft
                    - lora
                    - --lora_r
                    - "32"
                    - --lora_alpha
                    - "64"
                    - --lora_dropout
                    - "0.05"
                    - --vision_lr
                    - "1e-5"
                    - --loss_type
                    - contrastive_mse
                    - --return_mode
                    - nstep
                    - --mse_loss_weight
                    - "0.5"
                    - --max_grad_norm
                    - "1.0"
                    - --samples_per_epoch
                    - "50000"
                    - --vl_max_text_len
                    - "4700"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "67108864"
                        used: "16384"
                email: aparame@g.clemson.edu
                executable: /usr/bin/python3
                git:
                    commit: 8eefd4a67ec150bc07c50ecdc7fdb032fc984278
                    remote: git@github.com:shahils01/MA-VLCM.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-b33667ea-e143-ff5a-63da-fd80f357c8bb
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-91465355-3536-4315-bd21-726036c70993
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-1a8c7875-63db-bbda-fd4c-aa597cf41fad
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-1646e48f-8655-cf0e-8969-b4bb7f2f8e2e
                host: nodeau01.palmetto.clemson.edu
                memory:
                    total: "1081451524096"
                os: Linux-4.18.0-553.50.1.el8_10.x86_64-x86_64-with-glibc2.35
                program: /home/aparame/Research/MA-VLCM/train.py
                python: CPython 3.10.12
                root: /home/aparame/Research/MA-VLCM
                slurm:
                    cluster_name: palmetto2
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus: a100:4
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: cuuser_yue6_vae_verification
                    job_cpus_per_node: "32"
                    job_end_time: "1772269089"
                    job_gid: "10000"
                    job_gpus: 4,5,6,7
                    job_id: "9912436"
                    job_name: ma_vlcm_train
                    job_nodelist: nodeau01
                    job_num_nodes: "1"
                    job_partition: work1
                    job_qos: normal
                    job_start_time: "1772009889"
                    job_uid: "432600"
                    job_user: aparame
                    jobid: "9912436"
                    localid: "0"
                    mem_per_node: "262144"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nodeau01
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nodeau01
                    submit_dir: /home/aparame/Research/MA-VLCM
                    submit_host: vm-slurm-p-login01.palmetto.clemson.edu
                    task_pid: "4009601"
                    tasks_per_node: "1"
                    topology_addr: ndrspine.hdrspine.hdrleaf5.nodeau01
                    topology_addr_pattern: switch.switch.switch.node
                    tres_per_task: cpu=32
                startedAt: "2026-02-25T08:58:28.650556Z"
                writerId: zxp9grbtejh7bczqjxjho4k3tlg8jpdf
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 49
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 77
                - 98
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.24.2
            "8":
                - 2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 6
clip_len:
    value: 16
clip_stride:
    value: 1
compile:
    value: false
contrastive_margin:
    value: 0
d_model:
    value: 256
dataset_type:
    value: rware
ddp_find_unused_parameters:
    value: false
debug_out_dir:
    value: debug_samples
debug_save_video:
    value: false
done_reduce:
    value: any
epochs:
    value: 10
freeze_vision_tower:
    value: false
freeze_vl:
    value: true
fsdp:
    value: false
fsdp_cpu_offload:
    value: false
fsdp_min_num_params:
    value: 1000000
fsdp_use_orig_params:
    value: false
fusion_hidden:
    value: 512
gamma:
    value: 0.99
gnn_layers:
    value: 2
grad_accum_steps:
    value: 2
log_every:
    value: 50
lora_alpha:
    value: 64
lora_bias:
    value: none
lora_dropout:
    value: 0.05
lora_r:
    value: 32
lora_target_modules:
    value: ""
loss_type:
    value: contrastive_mse
lr:
    value: 0.0003
max_grad_norm:
    value: 1
mixed_precision:
    value: bf16
moe_experts:
    value: 4
moe_top_k:
    value: 2
mse_loss_weight:
    value: 0.5
n_step:
    value: 50
num_robots:
    value: 5
num_workers:
    value: 16
offroad_num_robots:
    value: 5
offroad_shards:
    value: /scratch/aparame/Research/VLCM_Data_Collection/OFFROAD/dataset_2
peft:
    value: lora
preprocess_in_loader:
    value: true
quantization_config:
    value: null
resize_height:
    value: 336
resize_width:
    value: 672
return_mode:
    value: nstep
reward_reduce:
    value: mean
robot_obs_dim:
    value: 8
robot_source:
    value: obs
rware_config:
    value: mixed-rware
samples_per_epoch:
    value: 50000
save_dir:
    value: /scratch/aparame/Research/VLCM_checkpoints
temporal_dropout:
    value: 0.1
temporal_heads:
    value: 4
temporal_layers:
    value: 2
text_dim:
    value: 512
text_mode:
    value: raw
text_prompt_template:
    value: null
train_shards:
    value: /scratch/aparame/Research/VLCM_Data_Collection/RWARE/data_scratch
use_moe:
    value: false
val_shards:
    value: ""
val_split:
    value: 0.2
video_channels:
    value: 3
video_frames:
    value: 8
video_mean:
    value:
        - 0.5
        - 0.5
        - 0.5
video_preprocessed:
    value: true
video_std:
    value:
        - 0.5
        - 0.5
        - 0.5
vision_lr:
    value: 1e-05
vl_backend:
    value: llava_video
vl_dtype:
    value: bfloat16
vl_max_text_len:
    value: 4700
vl_model_name:
    value: llava-hf/LLaVA-NeXT-Video-7B-32K-hf
weight_decay:
    value: 0.01
