_wandb:
    value:
        cli_version: 0.24.2
        e:
            tmkfaae9gsf62gzyitcmgmqoar0de6u3:
                args:
                    - --train_shards
                    - /scratch/aparame/Research/VLCM_Data_Collection/RWARE/data_scratch
                    - --offroad_shards
                    - /scratch/aparame/Research/VLCM_Data_Collection/OFFROAD/Varied_Traversability_new
                    - --offroad_num_robots
                    - "8"
                    - --dataset_type
                    - rware
                    - --rware_config
                    - mixed-rware
                    - --batch_size
                    - "8"
                    - --grad_accum_steps
                    - "4"
                    - --clip_len
                    - "16"
                    - --num_robots
                    - "8"
                    - --robot_obs_dim
                    - "8"
                    - --epochs
                    - "10"
                    - --vl_backend
                    - llava_video
                    - --vl_model_name
                    - llava-hf/LLaVA-NeXT-Video-7B-32K-hf
                    - --save_dir
                    - /scratch/aparame/Research/VLCM_checkpoints
                    - --num_workers
                    - "2"
                    - --mixed_precision
                    - bf16
                    - --freeze_vl
                    - --peft
                    - none
                    - --lora_r
                    - "16"
                    - --lora_alpha
                    - "32"
                    - --lora_dropout
                    - "0.05"
                    - --vision_lr
                    - "1e-5"
                    - --loss_type
                    - contrastive_mse
                    - --return_mode
                    - nstep
                    - --mse_loss_weight
                    - "0.01"
                    - --max_grad_norm
                    - "1.0"
                    - --samples_per_epoch
                    - "50000"
                    - --rware_visual_mode
                    - rware_only
                    - --gamma
                    - "0.95"
                    - --max_return_horizon
                    - "64"
                    - --ema_decay
                    - "0.995"
                    - --vl_max_text_len
                    - "4700"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 104
                cpu_count_logical: 104
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "67108864"
                        used: "16384"
                email: aparame@g.clemson.edu
                executable: /usr/bin/python3
                git:
                    commit: 083f64aefaaa0bc6c2eaf9c43e713abb97dc86f2
                    remote: git@github.com:shahils01/MA-VLCM.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-1ec74154-dd49-e546-e0b8-73f90d7e90e2
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-5532dc06-81ea-dd99-1270-bfa12be6d056
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-bc86f148-bc57-e761-b223-f3aa06bf1542
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-e1b68099-f854-3e9c-e428-fe9bce9dd746
                host: nodeai06.palmetto.clemson.edu
                memory:
                    total: "1081133400064"
                os: Linux-4.18.0-553.50.1.el8_10.x86_64-x86_64-with-glibc2.35
                program: /home/aparame/Research/MA-VLCM/train.py
                python: CPython 3.10.12
                root: /home/aparame/Research/MA-VLCM
                slurm:
                    cluster_name: palmetto2
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus: h100:4
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: cuuser_yue6_vae_verification
                    job_cpus_per_node: "32"
                    job_end_time: "1772572824"
                    job_gid: "10000"
                    job_gpus: 0,3,4,5
                    job_id: "10102761"
                    job_name: ma_vlcm_train
                    job_nodelist: nodeai06
                    job_num_nodes: "1"
                    job_partition: work1
                    job_qos: normal
                    job_start_time: "1772313624"
                    job_uid: "432600"
                    job_user: aparame
                    jobid: "10102761"
                    localid: "0"
                    mem_per_node: "262144"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nodeai06
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nodeai06
                    submit_dir: /home/aparame/Research/MA-VLCM
                    submit_host: vm-slurm-p-login02.palmetto.clemson.edu
                    task_pid: "1885506"
                    tasks_per_node: "1"
                    topology_addr: ndrspine.aindrspine.aindrleaf2.nodeai06
                    topology_addr_pattern: switch.switch.switch.node
                    tres_per_task: cpu=32
                startedAt: "2026-02-28T21:20:35.653627Z"
                writerId: tmkfaae9gsf62gzyitcmgmqoar0de6u3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 49
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 77
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.24.2
            "8":
                - 2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 8
clip_len:
    value: 16
clip_stride:
    value: 1
compile:
    value: false
contrastive_margin:
    value: 0
d_model:
    value: 256
dataset_type:
    value: rware
ddp_find_unused_parameters:
    value: false
debug_out_dir:
    value: debug_samples
debug_save_video:
    value: false
done_reduce:
    value: any
ema_decay:
    value: 0.995
epochs:
    value: 10
freeze_vision_tower:
    value: false
freeze_vl:
    value: true
fsdp:
    value: false
fsdp_cpu_offload:
    value: false
fsdp_min_num_params:
    value: 1000000
fsdp_use_orig_params:
    value: false
fusion_hidden:
    value: 512
gamma:
    value: 0.95
gnn_layers:
    value: 2
grad_accum_steps:
    value: 4
log_every:
    value: 50
lora_alpha:
    value: 32
lora_bias:
    value: none
lora_dropout:
    value: 0.05
lora_r:
    value: 16
lora_target_modules:
    value: ""
loss_type:
    value: contrastive_mse
lr:
    value: 0.0003
max_grad_norm:
    value: 1
max_return_horizon:
    value: 64
mixed_precision:
    value: bf16
moe_experts:
    value: 4
moe_top_k:
    value: 2
mse_loss_weight:
    value: 0.01
n_step:
    value: 50
num_robots:
    value: 8
num_workers:
    value: 2
offroad_num_robots:
    value: 8
offroad_shards:
    value: /scratch/aparame/Research/VLCM_Data_Collection/OFFROAD/Varied_Traversability_new
peft:
    value: none
preprocess_in_loader:
    value: true
quantization_config:
    value: null
resize_height:
    value: 336
resize_width:
    value: 672
return_mode:
    value: nstep
reward_reduce:
    value: mean
robot_obs_dim:
    value: 8
robot_source:
    value: obs
run_name:
    value: 50StepReturn_ContrastiveMSE_20260228_162031
rware_config:
    value: mixed-rware
rware_visual_mode:
    value: rware_only
samples_per_epoch:
    value: 50000
save_dir:
    value: /scratch/aparame/Research/VLCM_checkpoints
temporal_dropout:
    value: 0.1
temporal_heads:
    value: 4
temporal_layers:
    value: 2
text_dim:
    value: 512
text_mode:
    value: raw
text_prompt_template:
    value: null
train_shards:
    value: /scratch/aparame/Research/VLCM_Data_Collection/RWARE/data_scratch
use_moe:
    value: false
val_shards:
    value: ""
val_split:
    value: 0.2
video_channels:
    value: 3
video_frames:
    value: 8
video_mean:
    value:
        - 0.5
        - 0.5
        - 0.5
video_preprocessed:
    value: true
video_std:
    value:
        - 0.5
        - 0.5
        - 0.5
vision_lr:
    value: 1e-05
vl_backend:
    value: llava_video
vl_dtype:
    value: bfloat16
vl_max_text_len:
    value: 4700
vl_model_name:
    value: llava-hf/LLaVA-NeXT-Video-7B-32K-hf
weight_decay:
    value: 0.01
